# Generated by Django 6.0.4 on 2026-04-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionChainSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('expiry_date', models.DateField()),
                ('strike_price', models.FloatField()),
                ('option_type', models.CharField(max_length=2)),
                ('last_price', models.FloatField()),
                ('open_interest', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
